"""growth suite and calling

Revision ID: 3a2719b3c6af
Revises: c83e5340940a
Create Date: 2026-10-03 11:10:58.188125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a2719b3c6af'
down_revision: Union[str, Sequence[str], None] = 'c83e5340940a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submissions', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='app'
    )
    op.create_index(op.f('ix_app_forms_workspace_id'), 'forms', ['workspace_id'], unique=False, schema='app')
    op.create_table('incoming_hooks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token', sa.String(length=48), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('last_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='app'
    )
    op.create_index(op.f('ix_app_incoming_hooks_workspace_id'), 'incoming_hooks', ['workspace_id'], unique=False, schema='app')
    op.create_table('integrations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enc_secret', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'type'),
    schema='app'
    )
    op.create_index(op.f('ix_app_integrations_workspace_id'), 'integrations', ['workspace_id'], unique=False, schema='app')
    op.create_table('pages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('theme', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='app'
    )
    op.create_index(op.f('ix_app_pages_workspace_id'), 'pages', ['workspace_id'], unique=False, schema='app')
    op.create_table('payment_links',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=True),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('provider_ref', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_payment_links_contact_id'), 'payment_links', ['contact_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_payment_links_provider_ref'), 'payment_links', ['provider_ref'], unique=False, schema='app')
    op.create_index(op.f('ix_app_payment_links_workspace_id'), 'payment_links', ['workspace_id'], unique=False, schema='app')
    op.create_table('review_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=True),
    sa.Column('token', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='app'
    )
    op.create_index(op.f('ix_app_review_requests_contact_id'), 'review_requests', ['contact_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_review_requests_workspace_id'), 'review_requests', ['workspace_id'], unique=False, schema='app')
    op.create_table('form_submissions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('form_id', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['app.forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_form_submissions_contact_id'), 'form_submissions', ['contact_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_form_submissions_form_id'), 'form_submissions', ['form_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_form_submissions_workspace_id'), 'form_submissions', ['workspace_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_form_submissions_workspace_id'), table_name='form_submissions', schema='app')
    op.drop_index(op.f('ix_app_form_submissions_form_id'), table_name='form_submissions', schema='app')
    op.drop_index(op.f('ix_app_form_submissions_contact_id'), table_name='form_submissions', schema='app')
    op.drop_table('form_submissions', schema='app')
    op.drop_index(op.f('ix_app_review_requests_workspace_id'), table_name='review_requests', schema='app')
    op.drop_index(op.f('ix_app_review_requests_contact_id'), table_name='review_requests', schema='app')
    op.drop_table('review_requests', schema='app')
    op.drop_index(op.f('ix_app_payment_links_workspace_id'), table_name='payment_links', schema='app')
    op.drop_index(op.f('ix_app_payment_links_provider_ref'), table_name='payment_links', schema='app')
    op.drop_index(op.f('ix_app_payment_links_contact_id'), table_name='payment_links', schema='app')
    op.drop_table('payment_links', schema='app')
    op.drop_index(op.f('ix_app_pages_workspace_id'), table_name='pages', schema='app')
    op.drop_table('pages', schema='app')
    op.drop_index(op.f('ix_app_integrations_workspace_id'), table_name='integrations', schema='app')
    op.drop_table('integrations', schema='app')
    op.drop_index(op.f('ix_app_incoming_hooks_workspace_id'), table_name='incoming_hooks', schema='app')
    op.drop_table('incoming_hooks', schema='app')
    op.drop_index(op.f('ix_app_forms_workspace_id'), table_name='forms', schema='app')
    op.drop_table('forms', schema='app')
    # ### end Alembic commands ###
