"""initial schema

Revision ID: c83e5340940a
Revises: 
Create Date: 2026-10-03 01:17:23.240142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c83e5340940a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_jobs_status'), 'jobs', ['status'], unique=False, schema='app')
    op.create_index(op.f('ix_app_jobs_type'), 'jobs', ['type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_jobs_workspace_id'), 'jobs', ['workspace_id'], unique=False, schema='app')
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('clerk_org_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('branding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('onboarding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trial_llm_calls', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['app.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_org_id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_workspaces_slug'), 'workspaces', ['slug'], unique=False, schema='app')
    op.create_table('activities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_activities_contact_id'), 'activities', ['contact_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_activities_workspace_id'), 'activities', ['workspace_id'], unique=False, schema='app')
    op.create_table('agents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_version', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_key'),
    schema='app'
    )
    op.create_index(op.f('ix_app_agents_workspace_id'), 'agents', ['workspace_id'], unique=False, schema='app')
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_api_keys_prefix'), 'api_keys', ['prefix'], unique=False, schema='app')
    op.create_index(op.f('ix_app_api_keys_workspace_id'), 'api_keys', ['workspace_id'], unique=False, schema='app')
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_audit_log_workspace_id'), 'audit_log', ['workspace_id'], unique=False, schema='app')
    op.create_table('automations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trigger', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_automations_workspace_id'), 'automations', ['workspace_id'], unique=False, schema='app')
    op.create_table('calendars',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('availability', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='app'
    )
    op.create_index(op.f('ix_app_calendars_workspace_id'), 'calendars', ['workspace_id'], unique=False, schema='app')
    op.create_table('calls',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('transport', sa.String(length=16), nullable=False),
    sa.Column('from_number', sa.String(length=32), nullable=True),
    sa.Column('to_number', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('disposition', sa.String(length=64), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('recording_path', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_calls_agent_id'), 'calls', ['agent_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_calls_conversation_id'), 'calls', ['conversation_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_calls_workspace_id'), 'calls', ['workspace_id'], unique=False, schema='app')
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_campaigns_workspace_id'), 'campaigns', ['workspace_id'], unique=False, schema='app')
    op.create_table('companies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=32), nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_companies_workspace_id'), 'companies', ['workspace_id'], unique=False, schema='app')
    op.create_table('contacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('lifecycle', sa.String(length=24), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('source_channel', sa.String(length=16), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_contacts_email'), 'contacts', ['email'], unique=False, schema='app')
    op.create_index(op.f('ix_app_contacts_phone'), 'contacts', ['phone'], unique=False, schema='app')
    op.create_index(op.f('ix_app_contacts_workspace_id'), 'contacts', ['workspace_id'], unique=False, schema='app')
    op.create_table('dnd_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'value'),
    schema='app'
    )
    op.create_index(op.f('ix_app_dnd_entries_workspace_id'), 'dnd_entries', ['workspace_id'], unique=False, schema='app')
    op.create_table('eval_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('suite_id', sa.String(length=32), nullable=True),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_eval_runs_agent_id'), 'eval_runs', ['agent_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_eval_runs_suite_id'), 'eval_runs', ['suite_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_eval_runs_workspace_id'), 'eval_runs', ['workspace_id'], unique=False, schema='app')
    op.create_table('eval_suites',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('cases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_eval_suites_agent_id'), 'eval_suites', ['agent_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_eval_suites_workspace_id'), 'eval_suites', ['workspace_id'], unique=False, schema='app')
    op.create_table('golden_answers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_golden_answers_agent_id'), 'golden_answers', ['agent_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_golden_answers_workspace_id'), 'golden_answers', ['workspace_id'], unique=False, schema='app')
    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_knowledge_bases_workspace_id'), 'knowledge_bases', ['workspace_id'], unique=False, schema='app')
    op.create_table('members',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('teams', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_members_user_id'), 'members', ['user_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_members_workspace_id'), 'members', ['workspace_id'], unique=False, schema='app')
    op.create_table('notes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=True),
    sa.Column('deal_id', sa.String(length=32), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_notes_contact_id'), 'notes', ['contact_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_notes_workspace_id'), 'notes', ['workspace_id'], unique=False, schema='app')
    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_notifications_workspace_id'), 'notifications', ['workspace_id'], unique=False, schema='app')
    op.create_table('pipelines',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_pipelines_workspace_id'), 'pipelines', ['workspace_id'], unique=False, schema='app')
    op.create_table('provider_credentials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('enc_payload', sa.Text(), nullable=False),
    sa.Column('masked', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'provider'),
    schema='app'
    )
    op.create_index(op.f('ix_app_provider_credentials_workspace_id'), 'provider_credentials', ['workspace_id'], unique=False, schema='app')
    op.create_table('review_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=True),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('bad_answer', sa.Text(), nullable=False),
    sa.Column('proposed_answer', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_review_items_agent_id'), 'review_items', ['agent_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_review_items_workspace_id'), 'review_items', ['workspace_id'], unique=False, schema='app')
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('provider_ref', sa.String(length=128), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_subscriptions_workspace_id'), 'subscriptions', ['workspace_id'], unique=False, schema='app')
    op.create_table('tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('priority', sa.String(length=12), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=True),
    sa.Column('deal_id', sa.String(length=32), nullable=True),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('assignee_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_tasks_contact_id'), 'tasks', ['contact_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_tasks_workspace_id'), 'tasks', ['workspace_id'], unique=False, schema='app')
    op.create_table('tools',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enc_secret', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_tools_workspace_id'), 'tools', ['workspace_id'], unique=False, schema='app')
    op.create_table('traces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_traces_conversation_id'), 'traces', ['conversation_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_traces_workspace_id'), 'traces', ['workspace_id'], unique=False, schema='app')
    op.create_table('usage_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_usage_events_workspace_id'), 'usage_events', ['workspace_id'], unique=False, schema='app')
    op.create_index('ix_usage_ws_created', 'usage_events', ['workspace_id', 'created_at'], unique=False, schema='app')
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_webhook_endpoints_workspace_id'), 'webhook_endpoints', ['workspace_id'], unique=False, schema='app')
    op.create_table('agent_knowledge',
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('kb_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['app.agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kb_id'], ['app.knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'kb_id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_agent_knowledge_workspace_id'), 'agent_knowledge', ['workspace_id'], unique=False, schema='app')
    op.create_table('agent_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['app.agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_agent_versions_agent_id'), 'agent_versions', ['agent_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_agent_versions_workspace_id'), 'agent_versions', ['workspace_id'], unique=False, schema='app')
    op.create_table('appointments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('calendar_id', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['app.calendars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_appointments_calendar_id'), 'appointments', ['calendar_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_appointments_contact_id'), 'appointments', ['contact_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_appointments_start_at'), 'appointments', ['start_at'], unique=False, schema='app')
    op.create_index(op.f('ix_app_appointments_workspace_id'), 'appointments', ['workspace_id'], unique=False, schema='app')
    op.create_table('automation_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('automation_id', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['app.automations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_automation_runs_automation_id'), 'automation_runs', ['automation_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_automation_runs_workspace_id'), 'automation_runs', ['workspace_id'], unique=False, schema='app')
    op.create_table('campaign_targets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['app.campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_campaign_targets_campaign_id'), 'campaign_targets', ['campaign_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_campaign_targets_workspace_id'), 'campaign_targets', ['workspace_id'], unique=False, schema='app')
    op.create_table('channels',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enc_secret', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['app.agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_channels_agent_id'), 'channels', ['agent_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_channels_workspace_id'), 'channels', ['workspace_id'], unique=False, schema='app')
    op.create_table('contact_facts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_conversation_id', sa.String(length=32), nullable=True),
    sa.Column('source_channel', sa.String(length=16), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['app.contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_contact_facts_contact_id'), 'contact_facts', ['contact_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_contact_facts_workspace_id'), 'contact_facts', ['workspace_id'], unique=False, schema='app')
    op.create_table('contact_identities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('value', sa.String(length=254), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['app.contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'type', 'value'),
    schema='app'
    )
    op.create_index(op.f('ix_app_contact_identities_contact_id'), 'contact_identities', ['contact_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_contact_identities_workspace_id'), 'contact_identities', ['workspace_id'], unique=False, schema='app')
    op.create_table('conversations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('channel_ref', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('assignee_id', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.Column('csat', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['app.agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['app.contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_conversations_agent_id'), 'conversations', ['agent_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_conversations_channel_ref'), 'conversations', ['channel_ref'], unique=False, schema='app')
    op.create_index(op.f('ix_app_conversations_contact_id'), 'conversations', ['contact_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False, schema='app')
    op.create_index('ix_conv_ws_last', 'conversations', ['workspace_id', 'last_message_at'], unique=False, schema='app')
    op.create_table('deals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('pipeline_id', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['app.pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_deals_contact_id'), 'deals', ['contact_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_deals_pipeline_id'), 'deals', ['pipeline_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_deals_workspace_id'), 'deals', ['workspace_id'], unique=False, schema='app')
    op.create_table('knowledge_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('kb_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('chunks', sa.Integer(), nullable=False),
    sa.Column('when_to_use', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('refresh_days', sa.Integer(), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['app.knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_knowledge_sources_kb_id'), 'knowledge_sources', ['kb_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_knowledge_sources_workspace_id'), 'knowledge_sources', ['workspace_id'], unique=False, schema='app')
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('endpoint_id', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['app.webhook_endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_webhook_deliveries_endpoint_id'), 'webhook_deliveries', ['endpoint_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_webhook_deliveries_workspace_id'), 'webhook_deliveries', ['workspace_id'], unique=False, schema='app')
    op.create_table('chunks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('kb_id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['app.knowledge_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_chunks_kb_id'), 'chunks', ['kb_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_chunks_source_id'), 'chunks', ['source_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_chunks_workspace_id'), 'chunks', ['workspace_id'], unique=False, schema='app')
    op.create_table('datasets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('kb_id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('schema_card', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['app.knowledge_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_datasets_kb_id'), 'datasets', ['kb_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_datasets_workspace_id'), 'datasets', ['workspace_id'], unique=False, schema='app')
    op.create_table('handoffs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('urgency', sa.String(length=12), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('team', sa.String(length=64), nullable=True),
    sa.Column('assignee_id', sa.String(length=64), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['app.conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_handoffs_conversation_id'), 'handoffs', ['conversation_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_handoffs_workspace_id'), 'handoffs', ['workspace_id'], unique=False, schema='app')
    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ir', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('author_id', sa.String(length=64), nullable=True),
    sa.Column('channel_msg_id', sa.String(length=128), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.String(length=64), nullable=True),
    sa.Column('feedback', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['app.conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['app.workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_messages_conversation_id'), 'messages', ['conversation_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_messages_workspace_id'), 'messages', ['workspace_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_messages_workspace_id'), table_name='messages', schema='app')
    op.drop_index(op.f('ix_app_messages_conversation_id'), table_name='messages', schema='app')
    op.drop_table('messages', schema='app')
    op.drop_index(op.f('ix_app_handoffs_workspace_id'), table_name='handoffs', schema='app')
    op.drop_index(op.f('ix_app_handoffs_conversation_id'), table_name='handoffs', schema='app')
    op.drop_table('handoffs', schema='app')
    op.drop_index(op.f('ix_app_datasets_workspace_id'), table_name='datasets', schema='app')
    op.drop_index(op.f('ix_app_datasets_kb_id'), table_name='datasets', schema='app')
    op.drop_table('datasets', schema='app')
    op.drop_index(op.f('ix_app_chunks_workspace_id'), table_name='chunks', schema='app')
    op.drop_index(op.f('ix_app_chunks_source_id'), table_name='chunks', schema='app')
    op.drop_index(op.f('ix_app_chunks_kb_id'), table_name='chunks', schema='app')
    op.drop_table('chunks', schema='app')
    op.drop_index(op.f('ix_app_webhook_deliveries_workspace_id'), table_name='webhook_deliveries', schema='app')
    op.drop_index(op.f('ix_app_webhook_deliveries_endpoint_id'), table_name='webhook_deliveries', schema='app')
    op.drop_table('webhook_deliveries', schema='app')
    op.drop_index(op.f('ix_app_knowledge_sources_workspace_id'), table_name='knowledge_sources', schema='app')
    op.drop_index(op.f('ix_app_knowledge_sources_kb_id'), table_name='knowledge_sources', schema='app')
    op.drop_table('knowledge_sources', schema='app')
    op.drop_index(op.f('ix_app_deals_workspace_id'), table_name='deals', schema='app')
    op.drop_index(op.f('ix_app_deals_pipeline_id'), table_name='deals', schema='app')
    op.drop_index(op.f('ix_app_deals_contact_id'), table_name='deals', schema='app')
    op.drop_table('deals', schema='app')
    op.drop_index('ix_conv_ws_last', table_name='conversations', schema='app')
    op.drop_index(op.f('ix_app_conversations_workspace_id'), table_name='conversations', schema='app')
    op.drop_index(op.f('ix_app_conversations_contact_id'), table_name='conversations', schema='app')
    op.drop_index(op.f('ix_app_conversations_channel_ref'), table_name='conversations', schema='app')
    op.drop_index(op.f('ix_app_conversations_agent_id'), table_name='conversations', schema='app')
    op.drop_table('conversations', schema='app')
    op.drop_index(op.f('ix_app_contact_identities_workspace_id'), table_name='contact_identities', schema='app')
    op.drop_index(op.f('ix_app_contact_identities_contact_id'), table_name='contact_identities', schema='app')
    op.drop_table('contact_identities', schema='app')
    op.drop_index(op.f('ix_app_contact_facts_workspace_id'), table_name='contact_facts', schema='app')
    op.drop_index(op.f('ix_app_contact_facts_contact_id'), table_name='contact_facts', schema='app')
    op.drop_table('contact_facts', schema='app')
    op.drop_index(op.f('ix_app_channels_workspace_id'), table_name='channels', schema='app')
    op.drop_index(op.f('ix_app_channels_agent_id'), table_name='channels', schema='app')
    op.drop_table('channels', schema='app')
    op.drop_index(op.f('ix_app_campaign_targets_workspace_id'), table_name='campaign_targets', schema='app')
    op.drop_index(op.f('ix_app_campaign_targets_campaign_id'), table_name='campaign_targets', schema='app')
    op.drop_table('campaign_targets', schema='app')
    op.drop_index(op.f('ix_app_automation_runs_workspace_id'), table_name='automation_runs', schema='app')
    op.drop_index(op.f('ix_app_automation_runs_automation_id'), table_name='automation_runs', schema='app')
    op.drop_table('automation_runs', schema='app')
    op.drop_index(op.f('ix_app_appointments_workspace_id'), table_name='appointments', schema='app')
    op.drop_index(op.f('ix_app_appointments_start_at'), table_name='appointments', schema='app')
    op.drop_index(op.f('ix_app_appointments_contact_id'), table_name='appointments', schema='app')
    op.drop_index(op.f('ix_app_appointments_calendar_id'), table_name='appointments', schema='app')
    op.drop_table('appointments', schema='app')
    op.drop_index(op.f('ix_app_agent_versions_workspace_id'), table_name='agent_versions', schema='app')
    op.drop_index(op.f('ix_app_agent_versions_agent_id'), table_name='agent_versions', schema='app')
    op.drop_table('agent_versions', schema='app')
    op.drop_index(op.f('ix_app_agent_knowledge_workspace_id'), table_name='agent_knowledge', schema='app')
    op.drop_table('agent_knowledge', schema='app')
    op.drop_index(op.f('ix_app_webhook_endpoints_workspace_id'), table_name='webhook_endpoints', schema='app')
    op.drop_table('webhook_endpoints', schema='app')
    op.drop_index('ix_usage_ws_created', table_name='usage_events', schema='app')
    op.drop_index(op.f('ix_app_usage_events_workspace_id'), table_name='usage_events', schema='app')
    op.drop_table('usage_events', schema='app')
    op.drop_index(op.f('ix_app_traces_workspace_id'), table_name='traces', schema='app')
    op.drop_index(op.f('ix_app_traces_conversation_id'), table_name='traces', schema='app')
    op.drop_table('traces', schema='app')
    op.drop_index(op.f('ix_app_tools_workspace_id'), table_name='tools', schema='app')
    op.drop_table('tools', schema='app')
    op.drop_index(op.f('ix_app_tasks_workspace_id'), table_name='tasks', schema='app')
    op.drop_index(op.f('ix_app_tasks_contact_id'), table_name='tasks', schema='app')
    op.drop_table('tasks', schema='app')
    op.drop_index(op.f('ix_app_subscriptions_workspace_id'), table_name='subscriptions', schema='app')
    op.drop_table('subscriptions', schema='app')
    op.drop_index(op.f('ix_app_review_items_workspace_id'), table_name='review_items', schema='app')
    op.drop_index(op.f('ix_app_review_items_agent_id'), table_name='review_items', schema='app')
    op.drop_table('review_items', schema='app')
    op.drop_index(op.f('ix_app_provider_credentials_workspace_id'), table_name='provider_credentials', schema='app')
    op.drop_table('provider_credentials', schema='app')
    op.drop_index(op.f('ix_app_pipelines_workspace_id'), table_name='pipelines', schema='app')
    op.drop_table('pipelines', schema='app')
    op.drop_index(op.f('ix_app_notifications_workspace_id'), table_name='notifications', schema='app')
    op.drop_table('notifications', schema='app')
    op.drop_index(op.f('ix_app_notes_workspace_id'), table_name='notes', schema='app')
    op.drop_index(op.f('ix_app_notes_contact_id'), table_name='notes', schema='app')
    op.drop_table('notes', schema='app')
    op.drop_index(op.f('ix_app_members_workspace_id'), table_name='members', schema='app')
    op.drop_index(op.f('ix_app_members_user_id'), table_name='members', schema='app')
    op.drop_table('members', schema='app')
    op.drop_index(op.f('ix_app_knowledge_bases_workspace_id'), table_name='knowledge_bases', schema='app')
    op.drop_table('knowledge_bases', schema='app')
    op.drop_index(op.f('ix_app_golden_answers_workspace_id'), table_name='golden_answers', schema='app')
    op.drop_index(op.f('ix_app_golden_answers_agent_id'), table_name='golden_answers', schema='app')
    op.drop_table('golden_answers', schema='app')
    op.drop_index(op.f('ix_app_eval_suites_workspace_id'), table_name='eval_suites', schema='app')
    op.drop_index(op.f('ix_app_eval_suites_agent_id'), table_name='eval_suites', schema='app')
    op.drop_table('eval_suites', schema='app')
    op.drop_index(op.f('ix_app_eval_runs_workspace_id'), table_name='eval_runs', schema='app')
    op.drop_index(op.f('ix_app_eval_runs_suite_id'), table_name='eval_runs', schema='app')
    op.drop_index(op.f('ix_app_eval_runs_agent_id'), table_name='eval_runs', schema='app')
    op.drop_table('eval_runs', schema='app')
    op.drop_index(op.f('ix_app_dnd_entries_workspace_id'), table_name='dnd_entries', schema='app')
    op.drop_table('dnd_entries', schema='app')
    op.drop_index(op.f('ix_app_contacts_workspace_id'), table_name='contacts', schema='app')
    op.drop_index(op.f('ix_app_contacts_phone'), table_name='contacts', schema='app')
    op.drop_index(op.f('ix_app_contacts_email'), table_name='contacts', schema='app')
    op.drop_table('contacts', schema='app')
    op.drop_index(op.f('ix_app_companies_workspace_id'), table_name='companies', schema='app')
    op.drop_table('companies', schema='app')
    op.drop_index(op.f('ix_app_campaigns_workspace_id'), table_name='campaigns', schema='app')
    op.drop_table('campaigns', schema='app')
    op.drop_index(op.f('ix_app_calls_workspace_id'), table_name='calls', schema='app')
    op.drop_index(op.f('ix_app_calls_conversation_id'), table_name='calls', schema='app')
    op.drop_index(op.f('ix_app_calls_agent_id'), table_name='calls', schema='app')
    op.drop_table('calls', schema='app')
    op.drop_index(op.f('ix_app_calendars_workspace_id'), table_name='calendars', schema='app')
    op.drop_table('calendars', schema='app')
    op.drop_index(op.f('ix_app_automations_workspace_id'), table_name='automations', schema='app')
    op.drop_table('automations', schema='app')
    op.drop_index(op.f('ix_app_audit_log_workspace_id'), table_name='audit_log', schema='app')
    op.drop_table('audit_log', schema='app')
    op.drop_index(op.f('ix_app_api_keys_workspace_id'), table_name='api_keys', schema='app')
    op.drop_index(op.f('ix_app_api_keys_prefix'), table_name='api_keys', schema='app')
    op.drop_table('api_keys', schema='app')
    op.drop_index(op.f('ix_app_agents_workspace_id'), table_name='agents', schema='app')
    op.drop_table('agents', schema='app')
    op.drop_index(op.f('ix_app_activities_workspace_id'), table_name='activities', schema='app')
    op.drop_index(op.f('ix_app_activities_contact_id'), table_name='activities', schema='app')
    op.drop_table('activities', schema='app')
    op.drop_index(op.f('ix_app_workspaces_slug'), table_name='workspaces', schema='app')
    op.drop_table('workspaces', schema='app')
    op.drop_index(op.f('ix_app_jobs_workspace_id'), table_name='jobs', schema='app')
    op.drop_index(op.f('ix_app_jobs_type'), table_name='jobs', schema='app')
    op.drop_index(op.f('ix_app_jobs_status'), table_name='jobs', schema='app')
    op.drop_table('jobs', schema='app')
    # ### end Alembic commands ###
